### ISSUE TITLE
Modulo com link da imagem sem funcionar

### ISSUE THREAD

**Issue by invaderhd** [ifthenpay/multibanco-prestashop#1]
Neste módulo é usado várias vezes o link "http://dl.dropbox.com/u/14494130/ifmb/imagensmodulos/mb.gif".
Problemas: 

1.  Link não funciona
2. Não é usado https.

Sugestões coloquem a imagem localmente directamente dentro do módulo, não usem links http metam sempre https afinal isto é um módulo de pagamentos.

**Comment by manuelrocha88** [comment]
Caro @invaderhd,

Essa situação já tinha sido detetada e já tinha sido corrigido para a versão PS1.6 no commit 73a271a295ef2ff6d6a06422299b58bca2e31618 e para a versão PS1.7 no commit 86437aa36cc8289f0ceeb8a40dd44bd4780e5479.

Vou dar o seu issue como resolvido.

Qualquer situação disponha.

**Comment by invaderhd** [comment]
Viva @manuelrocha88, agradeço a rapidez, apesar de ser programador não estou por dentro de como funciona os módulos para prestashop, quando detetei este problema fiz uma pesquisa global pelo link da imagem e encontrei diversos sitios onde é usado, por exemplo no ficheiro multibanco/mails/multibanco.html penso que este ficheiro seja o template do email.

Já agora para instalar a versão mais recente tenho que remover o módulo antigo, isso vai fazer com que tenha que pedir de novo para ativarem o calback?

**Comment by manuelrocha88** [comment]
Viva @invaderhd , basta substituir os conteúdo da sua pasta multibanco pelos novo conteúdo. Não necessita de desativar ou reconfigurar o módulo.
